cab/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('all-snippets/', views.SnippetLists, name="cab_snippet_list"),
    path('snippet/<int:snippet_id>', views.snippetDetail, name="cab_snippet_detail"),
    path("languages", views.languageList, name="cab_language_list"),
    path("languages/<slug:slug_lang>", views.languageDetail, name="cab_language_detail"),
    path("author", views.authorList, name="cab_author_list"),
    path("add-snippet", views.add_snippet,name="cab_snippet_add"),
    path("edit-snippet/<int:snippet_id>", views.edit_snippet, name="cab_snippet_edit"),
    path("add-bookmark/<int:snippet_id>/", views.add_bookmark, name="cab_bookmark_add"),
    path("delete-bookmark/<int:snippet_id>/", views.delete_bookmark, name="cab_bookmark_delete"),
    path("user-bookmarks", views.user_bookmarks, name="cab_user_bookmarks"),
    path("add-rating/<int:snippet_id>/", views.rateAdd,name="cab_rating_add"),

]

code_sharing/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("cab.urls")),
]



if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cab/models.py
import datetime
from pyexpat import model
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


from django.utils.translation import gettext_lazy as _

# ? Current Active User Model
User = get_user_model()

# ? Import Local Manager
from . import managers


# ? Third-Party Imports
# from pygments import lexers
from pygments import (
    formatters, 
    highlight, 
    lexers
)
from tagging.fields import TagField
from markdown import markdown

# Create your models here.

class Language(models.Model):
    name = models.CharField(max_length=100, help_text = _("The name of the language"))
    slug = models.SlugField(unique=True , help_text = _("A unique slug to identify it in URLs"))
    language_code = models.CharField(max_length=50 , help_text = _("A language code that pygments can use to load the appropriate syntax-highlighting module"))
    mime_type = models.CharField(max_length=100 , help_text = _("A MIME type to use when sending a snippet file in this language"))


    # ? Managers
    objects = models.Manager()
    top_objects = managers.LanguageManager()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cab_language_detail', args=[self.slug])

    def get_lexer(self):
        return lexers.get_lexer_by_name(self.language_code)

    

    

class Snippet(models.Model):
    title = models.CharField(max_length=255)
    language = models.ForeignKey(Language, on_delete=models.CASCADE , help_text= _("A foreign key pointing at the Language the snippet is written in"))
    author = models.ForeignKey(User, on_delete=models.CASCADE, help_text = _("A foreign key to Django’s User model to represent the snippet’s author."))
    description = models.TextField()
    description_html = models.TextField(editable=False)
    code = models.TextField(help_text=_("The actual code"))
    highlighted_code = models.TextField(editable=False, help_text=_("Syntax-highlighted HTML version separate from the original code"))
    tags = TagField( help_text=_("A list of tags"))
    pub_date = models.DateTimeField(editable=False, help_text=_("The date and time when the snippet was first posted"))
    updated_date = models.DateTimeField(editable=False, help_text=_("The date and time when it was last updated"))


    class Meta:
        ordering = ['-pub_date']


    # ? Managers
    objects = models.Manager()
    score_objects = managers.SnippetManager()

    def __str__(self):
        return self.title

    def highlight(self):
        return highlight(
            self.code,
            self.language.get_lexer(),
            formatters.HtmlFormatter(linenos=True)
        )

    def save(self):
        if not self.id:
            self.pub_date = datetime.datetime.now()
        self.updated_date = datetime.datetime.now()
        self.description_html = markdown(self.description)
        self.highlighted_code = self.highlight()
        super(Snippet, self).save()

    def get_absolute_url(self):
        return reverse('cab_snippet_detail', args=[self.id])


class Bookmark(models.Model):
    snippet = models.ForeignKey(Snippet , on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='cab_bookmarks' , on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-date']

    def __str__(self):
        return "%s bookmarked by %s" % (self.snippet, self.user)


class Rating(models.Model):
    RATING_UP = 1
    RATING_DOWN = -1
    RATING_CHOICES = ((RATING_UP, 'useful'),
    (RATING_DOWN, 'not useful'))
    snippet = models.ForeignKey(Snippet , on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='cab_rating', on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return "%s rating %s (%s)" % (self.user, self.snippet,
        self.get_rating_display())

cab/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import (
    Snippet,
    Language
)

# ? Current Active User Model
User = get_user_model()


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        exclude = ['author']

cab/views.py
import sys
import logging
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden

# ? Current Active User Model
User = get_user_model()


logger = logging.getLogger(__name__)

# ? Import Local Models
from .models import (
    Snippet,
    Language,
    Bookmark,
    Rating
)

# ? Import Local Forms
from .forms import(
    SnippetForm
)

# ? Create your views here.

def index(request):
    template_name = 'cab/index.html'
    context = {
    }
    return render(request, template_name, context)


def SnippetLists(request):
    template_name = 'cab/snippet_list.html'
    snippets = Snippet.objects.all()
    context = {
        "snippets": snippets
    }
    return render(request, template_name, context)


def snippetDetail(request, snippet_id):
    template_name = 'cab/snippet_detail.html'
    try:
        snippet = Snippet.objects.get(id=snippet_id)
    except Snippet.DoesNotExist:
        messages.error(request, "Requested Snippet Does Not Exist.")
        return redirect(reverse("index"))
    except Exception as e:
        logger.error(e, exc_info=sys.exc_info())
        messages.error(
            request, "There might be some error caught. Try again after some time.")
        return redirect(reverse("index"))
    context = {
        "snippet": snippet
    }
    return render(request, template_name, context)


def languageList(request):
    template_name = 'cab/language_list.html'
    all_languages = Language.top_objects.top_languages()
    # print(all_languages)
    context = {
        "all_languages": all_languages
    }
    return render(request, template_name, context)


def languageDetail(request, slug_lang):
    template_name = 'cab/language_detail.html'
    try:
        lang = Language.objects.get(slug=slug_lang)
        snippets = lang.snippet_set.all()
    except Language.DoesNotExist:
        messages.error(request, "Requested Page Does Not Exist.")
        return redirect(reverse("index"))
    except Exception as e:
        logger.error(e, exc_info=sys.exc_info())
        messages.error(
            request, "There might be some error caught. Try again after some time.")
        return redirect(reverse("index"))
    context = {
        "snippets": snippets,
        "lang": lang
    }
    return render(request, template_name, context)


def authorList(request):
    template_name = 'cab/top_authors.html'
    all_authors = Snippet.score_objects.top_authors()
    context = {
        "all_authors": all_authors
    }
    return render(request, template_name, context)


@login_required
def add_snippet(request):
    template_name = "cab/add_snippet.html"
    if request.method == 'POST':
        form = SnippetForm(data=request.POST)
        if form.is_valid():
            new_snippet = form.save(commit=False)
            new_snippet.author = request.user
            new_snippet.save()
            return HttpResponseRedirect(new_snippet.get_absolute_url())
    else:
        form = SnippetForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required
def edit_snippet(request, snippet_id):
    template_name = 'cab/edit_snippet.html'
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    if request.user.id != snippet.author.id:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = SnippetForm(instance=snippet, data=request.POST)
        if form.is_valid():
            snippet = form.save()
            return HttpResponseRedirect(snippet.get_absolute_url())
    else:
        form = SnippetForm(instance=snippet)
    context = {'form': form, 'add': False}
    return render(request, template_name, context)


@login_required
def add_bookmark(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    try:
        Bookmark.objects.get(user__pk=request.user.id,snippet__pk=snippet.id)
        messages.info(request, "Already Bookmarked")
    except Bookmark.DoesNotExist:
        Bookmark.objects.create(user=request.user, snippet=snippet)
        messages.success(request, "Successfully Bookmarked")
    return HttpResponseRedirect(snippet.get_absolute_url())


@login_required
def delete_bookmark(request, snippet_id):
    template_name="cab/confirm_bookmark_delete.html"
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    if request.method == 'POST':
        Bookmark.objects.filter(user__pk=request.user.id, snippet__pk=snippet.id).delete()
        return HttpResponseRedirect(snippet.get_absolute_url())
    else:
        context= { 'snippet': snippet }
        return render(request, template_name, context)

@login_required
def user_bookmarks(request):
    template_name = 'cab/user_bookmark_list.html'
    user_bookmark_list = Bookmark.objects.filter(user = request.user)
    context = {
        "user_bookmark_list" : user_bookmark_list
    }
    return render(request, template_name, context)


def most_bookmarked(request):
    template_name='cab/most_bookmarked.html'
    bookmark_list = Snippet.score_objects.most_bookmarked()
    context = {
        "bookmark_list" : bookmark_list
    }
    return render(request, template_name, context)


@login_required
def rateAdd(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    if 'rating' not in request.GET or request.GET['rating'] not in ('1', '-1'):
        return HttpResponseRedirect(snippet.get_absolute_url())
    try:
        rating = Rating.objects.get(user__pk=request.user.id, snippet__pk=snippet.id)
    except Rating.DoesNotExist:
        rating = Rating(user=request.user, snippet=snippet)
    rating.rating = int(request.GET['rating'])
    rating.save()
    return HttpResponseRedirect(snippet.get_absolute_url())

cab/templates/cab/add_snippet.html
{% extends 'base.html' %}

{% block content %}
<h1>Add a snippet</h1>
<p>Use the form below to submit your snippet; all fields are
required.</p>
<form method="POST" action="{% url 'cab_snippet_add' %}">
    {% csrf_token %}
<p>{% if form.title.errors %}
<span class="error">
{{ form.title.errors|join:", " }}
</span>
{% endif %}</p>
<p><label for="id_title">Title:</label>
{{ form.title }}</p>
<p>{% if form.language.errors %}
<span class="error">
{{ form.language.errors|join:", " }}
</span>
{% endif %}</p>
<p><label for="id_languages">Language:</label>
    {{ form.language }}</p>
    <p>{% if form.description.errors %}
    <span class="error">
    {{ form.description.errors|join:", " }}
    </span>
    {% endif %}</p>
    <p><label for="id_description">Description:</label></p>
    <p>{{ form.description }}</p>
    <p>{% if form.code.errors %}
    <span class="error">
    {{ form.code.errors|join:", " }}
    </span>
    {% endif %}</p>
    <p><label for="id_code">Code:</label></p>
    <p>{{ form.code }}</p>
    <p>{% if form.tags.errors %}
    <span class="error">
    {{ form.tags.errors|join:", " }}
    </span>
    {% endif %}</p>
    <p><label for="id_tags">Tags:</label>
    {{ form.tags }}</p>
    <p><input type="submit" value="Submit"></p>
    </form>
{% endblock %}

cab/templates/cab/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block extra_css %}
    {% endblock extra_css %}
    <title>{% block title %}ShareCode{% endblock title %}</title>
</head>
<body>
    
    
    {% block header %}
        {% include 'header.html' %}
    {% endblock header %}


    {% include 'notification.html' %}

    {% block content %}
        


    {% endblock content %}

    {% block footer %}
    {% endblock footer %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extra_js %}
{% endblock extra_js %}
</body>
</html>

cab/templates/cab/confirm_bookmark_delete.html
{% load snippets %}

    {% if_bookmarked user snippet %}
        <form method="post" action="{% url 'cab_bookmark_delete' snippet.id %}">
            {% csrf_token %}
        <p><input type="submit" value="Delete bookmark"></p>
        </form>
{% else %}
<p><a href="{% url 'cab_bookmark_add' snippet.id %}">Add bookmark</a></p>
{% endif_bookmarked %}

cab/templates/cab/edit_snippet.html
{% extends 'base.html' %}

{% block content %}
<h1>{% if add %}Add a{% else %}Edit your{% endif %} snippet</h1>
<p>Use the form below to {% if add %}add{% else %}edit {% endif %}
your snippet; all fields are required</p>
<form method="post" action="">
    {%  csrf_token %}
{{ form.as_p }}
<p><input type="submit" value="Send"></p>
</form>
{% endblock %}

cab/templates/cab/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 fw-bolder" href="{% url 'index' %}">CodeShare</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'cab_snippet_list' %}">All Snippets</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'cab_language_list' %}">Languages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'cab_author_list' %}">Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'cab_snippet_add' %}">Add New Snippet</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'cab_user_bookmarks' %}">User Bookmarks</a>
          </li>
        </ul>
        
      </div>
    </div>
  </nav>

cab/templates/cab/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="fs-1 fw-bolder">
                    CodeShare
                </h1>
            </div>
        </div>
    </div>
{% endblock %}

cab/templates/cab/language_detail.html
{% extends 'base.html' %}


{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <h1 class="fs-1 fw-bolder">
                    All Code Snippets Written in {{ lang.name }}
                </h1>
            </div>
        </div>
        <div class="row justify-content-center my-5">
            <div class="col-12 ">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Tags</th>
                        <th scope="col">Publication Date</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for snippet in snippets  %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'cab_snippet_detail' snippet.id %}">{{ snippet.title }}</a></td>
                                <td>{{ snippet.author }}</td>
                                <td>{{ snippet.tags }}</td>
                                <td>{{ snippet.pub_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                
            </div>
        </div>
    </div>


{% endblock %}

cab/templates/cab/language_list.html
{% extends 'base.html' %}


{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <h1 class="fs-1 fw-bolder">
                    All Languages
                </h1>
            </div>
        </div>
        <div class="row justify-content-center my-5">
            <div class="col-12 col-md-6 ">
                        <ul class="list-group">
                            {% for language in all_languages %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <a href="{% url 'cab_language_detail' language.slug %}" class=" card-link text-decoration-none">{{ language.name }}</a>
                                    <span class="badge bg-primary rounded-pill">{{ language.score }}</span>
                                </li>
                            {% endfor %}
                          </ul>
                          
                
            </div>
        </div>
    </div>


{% endblock %}

cab/templates/cab/notification.html
{% if messages %}
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}

cab/templates/cab/snippet_detail.html
{% extends 'base.html' %}
{% load static snippets %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/pygments.css' %}">
    <style>
        td.linenos .normal {
            color: white;
        }
    </style>
{% endblock extra_css %}

{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <h1 class="fs-1 fw-bolder">
                    {{ snippet.title }}
                </h1>
                <p class="card-text">
                    <span class="fw-bolder">Author: </span> <span>{{ snippet.author }}</span> <span class="fw-bolder ms-2">Poster: </span> <span>{{ snippet.pub_date.date }}</span> <span class="fw-bolder ms-2">Language: </span> <span>{{ snippet.language|capfirst }}</span>
                </p>
            </div>
            <div class="col-12">
                <div class="card w-100 my-3">
                    <div class="card-body bg-dark">
                        {{ snippet.highlighted_code|safe|escape }}
                        
                    </div>
                    
                        <div class="card-footer">
                            {% if request.user == snippet.author %}
                                <a href="{% url 'cab_snippet_edit' snippet.id  %}" class="btn btn-primary d-block" >Edit Snippet</a>
                            {% endif %}
                            <a href="{% url 'cab_bookmark_add' snippet.id %}">Add Bookmark</a>
                            {% if_rated user snippet %}
                                {% get_rating user snippet as rating %}
                                <p>You rated this snippet {{ rating.get_rating_display }}.</p>
                                {% else %}
                                <p>Rate this snippet:
                                <a href="{% url 'cab_rating_add' snippet.id %}?rating=1">useful</a> or
                                <a href="{% url 'cab_rating_add' snippet.id %}?rating=-1">not useful</a>.</p>
                            {% endif_rated %}
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cab/templates/cab/snippet_list.html
{% extends 'base.html' %}


{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <h1 class="fs-1 fw-bolder">
                    All Code Snippets
                </h1>
            </div>
        </div>
        <div class="row justify-content-center my-5">
            <div class="col-12 ">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Tags</th>
                        <th scope="col">Publication Date</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for snippet in snippets  %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'cab_snippet_detail' snippet.id %}">{{ snippet.title }}</a></td>
                                <td>{{ snippet.author }}</td>
                                <td>{{ snippet.tags }}</td>
                                <td>{{ snippet.pub_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                
            </div>
        </div>
    </div>


{% endblock %}

cab/templates/cab/top_authors.html
{% extends 'base.html' %}


{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <h1 class="fs-1 fw-bolder">
                    All Authors
                </h1>
            </div>
        </div>
        <div class="row my-3">
            <div class="col-12">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Number of Snippets</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for author in all_authors %}
                            <tr>
                                <td>{{ author }}</td>
                                <td>{{ author.score }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
{% endblock %}

cab/templates/cab/user_bookmark_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-12">
                <h1 class="fs-1 fw-bolder">
                    User Bookmarks
                </h1>
            </div>
        </div>
        <div class="row justify-content-center my-5">
            <div class="col-12 col-md-6">
               
                    {% for bookmark  in user_bookmark_list %}
                        <ul class="list-group list-group-horizontal">
                            <li class="list-group-item w-100">{{ bookmark.snippet }}</li>
                            <li class="list-group-item w-100">{{ bookmark.date }}</li>
                            <li class="list-group-item w-100  "><a href="{% url 'cab_bookmark_delete' bookmark.snippet.id %}" class="card-link text-decoration-none">Delete Bookmark</a></li>
                        </ul>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}